// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/admin/Clientes" | "/admin/asistencia" | "/admin/conciliacion" | "/admin/configuracion" | "/admin/contabilidad" | "/admin/delete-july-temp" | "/admin/egresos" | "/admin/expediente" | "/admin/gastos" | "/admin/inventario" | "/admin/login" | "/admin/monitor" | "/admin/productos" | "/admin/proveedores" | "/admin/reconcile-temp" | "/admin/staff" | "/admin/ventas" | "/testenv" | "/tienda"
type AppRouteHandlerRoutes = "/admin/contabilidad/process-xml" | "/admin/gastos/process-xml" | "/api/zkteco/push"
type PageRoutes = never
type LayoutRoutes = "/" | "/admin"
type RedirectRoutes = never
type RewriteRoutes = "/iclock/cdata" | "/iclock/devicecmd" | "/iclock/getrequest"
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/admin": {}
  "/admin/asistencia": {}
  "/admin/Clientes": {}
  "/admin/conciliacion": {}
  "/admin/configuracion": {}
  "/admin/contabilidad": {}
  "/admin/contabilidad/process-xml": {}
  "/admin/delete-july-temp": {}
  "/admin/egresos": {}
  "/admin/expediente": {}
  "/admin/gastos": {}
  "/admin/gastos/process-xml": {}
  "/admin/inventario": {}
  "/admin/login": {}
  "/admin/monitor": {}
  "/admin/productos": {}
  "/admin/proveedores": {}
  "/admin/reconcile-temp": {}
  "/admin/staff": {}
  "/admin/ventas": {}
  "/api/zkteco/push": {}
  "/iclock/cdata": {}
  "/iclock/devicecmd": {}
  "/iclock/getrequest": {}
  "/testenv": {}
  "/tienda": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
  "/admin": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
