// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../../app/admin/Clientes/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/Clientes">> = Specific
  const handler = {} as typeof import("../../../app/admin/Clientes/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/asistencia/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/asistencia">> = Specific
  const handler = {} as typeof import("../../../app/admin/asistencia/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/conciliacion/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/conciliacion">> = Specific
  const handler = {} as typeof import("../../../app/admin/conciliacion/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/configuracion/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/configuracion">> = Specific
  const handler = {} as typeof import("../../../app/admin/configuracion/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/contabilidad/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/contabilidad">> = Specific
  const handler = {} as typeof import("../../../app/admin/contabilidad/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/delete-july-temp/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/delete-july-temp">> = Specific
  const handler = {} as typeof import("../../../app/admin/delete-july-temp/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/egresos/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/egresos">> = Specific
  const handler = {} as typeof import("../../../app/admin/egresos/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/expediente/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/expediente">> = Specific
  const handler = {} as typeof import("../../../app/admin/expediente/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/gastos/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/gastos">> = Specific
  const handler = {} as typeof import("../../../app/admin/gastos/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/inventario/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/inventario">> = Specific
  const handler = {} as typeof import("../../../app/admin/inventario/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/login">> = Specific
  const handler = {} as typeof import("../../../app/admin/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/monitor/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/monitor">> = Specific
  const handler = {} as typeof import("../../../app/admin/monitor/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/productos/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/productos">> = Specific
  const handler = {} as typeof import("../../../app/admin/productos/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/proveedores/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/proveedores">> = Specific
  const handler = {} as typeof import("../../../app/admin/proveedores/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/reconcile-temp/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/reconcile-temp">> = Specific
  const handler = {} as typeof import("../../../app/admin/reconcile-temp/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/staff/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/staff">> = Specific
  const handler = {} as typeof import("../../../app/admin/staff/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/ventas/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/ventas">> = Specific
  const handler = {} as typeof import("../../../app/admin/ventas/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../../app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/testenv/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/testenv">> = Specific
  const handler = {} as typeof import("../../../app/testenv/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/tienda/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/tienda">> = Specific
  const handler = {} as typeof import("../../../app/tienda/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/contabilidad/process-xml/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/admin/contabilidad/process-xml">> = Specific
  const handler = {} as typeof import("../../../app/admin/contabilidad/process-xml/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/gastos/process-xml/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/admin/gastos/process-xml">> = Specific
  const handler = {} as typeof import("../../../app/admin/gastos/process-xml/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/zkteco/push/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/zkteco/push">> = Specific
  const handler = {} as typeof import("../../../app/api/zkteco/push/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../../app/admin/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/admin">> = Specific
  const handler = {} as typeof import("../../../app/admin/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../../app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
